src/Entity/Evenement.php
<?php

namespace App\Entity;

use App\Repository\EvenementRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;


#[ORM\Entity(repositoryClass: EvenementRepository::class)]
class Evenement
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message:"Le nom ne doit pas être vide.")]
    #[Assert\Length(max:255, maxMessage:"Le nom ne peut pas dépasser {{ limit }} caractères.")]
    #[Assert\Type(type: "string", message: "Le nom doit être une chaîne de caractères.")]

    private ?string $nom = null;

    #[ORM\Column(type: "text")]
    #[Assert\NotBlank(message:"La description ne doit pas être vide.")]
    #[Assert\Length(min:10, maxMessage:"Description doit  dépasser {{ limit }} caractères.")]

    private ?string $description = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message:"Faut préciser le lieu ")]
    #[Assert\Length(max:255, maxMessage:"Lieu ne doit pas  dépasser {{ limit }} caractères.")]
    private ?string $lieu = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_evenement = null;

    #[ORM\OneToMany(targetEntity: Ticket::class, mappedBy: 'evenement' ,cascade: ["remove"])]
    private Collection $tickets;

    #[ORM\Column(length: 255)]
    private ?string $image_evenement = null;

    public function __construct()
    {
        $this->date_evenement = new \DateTime();
        $this->tickets = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getLieu(): ?string
    {
        return $this->lieu;
    }

    public function setLieu(string $lieu): static
    {
        $this->lieu = $lieu;

        return $this;
    }

    public function getDateEvenement(): ?\DateTimeInterface
    {
        return $this->date_evenement;
    }

    public function setDateEvenement(\DateTimeInterface $date_evenement): static
    {
        $this->date_evenement = $date_evenement;

        return $this;
    }

    public function setTickets(Collection $tickets): void
    {
        $this->tickets = $tickets;
    }

    /**
     * @return Collection<int, Ticket>
     */
    public function getTickets(): Collection
    {
        return $this->tickets;
    }

    public function addTicket(Ticket $ticket): static
    {
        if (!$this->tickets->contains($ticket)) {
            $this->tickets->add($ticket);
            $ticket->setEvenement($this);
        }

        return $this;
    }

    public function removeTicket(Ticket $ticket): static
    {
        if ($this->tickets->removeElement($ticket)) {
            // set the owning side to null (unless already changed)
            if ($ticket->getEvenement() === $this) {
                $ticket->setEvenement(null);
            }
        }

        return $this;
    }

    public function getImageEvenement(): ?string
    {
        return $this->image_evenement;
    }

    public function setImageEvenement(string $image_evenement): self
    {
        $this->image_evenement = $image_evenement;

        return $this;
    }

}

src/Controller/EvenementFrontController.php
<?php

namespace App\Controller;

use App\Entity\Evenement;
use App\Form\Evenement1Type;
use App\Repository\EvenementRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/front/evenement')]
class EvenementFrontController extends AbstractController
{
    #[Route('/', name: 'app_evenement_front_index', methods: ['GET'])]
    public function index(EvenementRepository $evenementRepository): Response
    {
        return $this->render('evenement_front/index.html.twig', [
            'evenements' => $evenementRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_evenement_front_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $evenement = new Evenement();
        $form = $this->createForm(Evenement1Type::class, $evenement);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($evenement);
            $entityManager->flush();

            return $this->redirectToRoute('app_evenement_front_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('evenement_front/new.html.twig', [
            'evenement' => $evenement,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_evenement_front_show', methods: ['GET'])]
    public function show(Evenement $evenement): Response
    {
        return $this->render('evenement_front/show.html.twig', [
            'evenement' => $evenement,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_evenement_front_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Evenement $evenement, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(Evenement1Type::class, $evenement);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_evenement_front_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('evenement_front/edit.html.twig', [
            'evenement' => $evenement,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_evenement_front_delete', methods: ['POST'])]
    public function delete(Request $request, Evenement $evenement, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$evenement->getId(), $request->request->get('_token'))) {
            $entityManager->remove($evenement);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_evenement_front_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/evenement_front/_delete_form.html.twig
<form method="post" action="{{ path('app_evenement_front_delete', {'id': evenement.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ evenement.id) }}">
    <button class="btn">Delete</button>
</form>

templates/evenement_front/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/evenement_front/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Evenement{% endblock %}

{% block body %}
    <h1>Edit Evenement</h1>

    {{ include('evenement_front/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_evenement_front_index') }}">back to list</a>

    {{ include('evenement_front/_delete_form.html.twig') }}
{% endblock %}

templates/evenement_front/index.html.twig
{% extends 'base1.html.twig' %}

{% block title %}Liste evenement{% endblock %}

{% block body %}
    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-section set-bg" data-setbg="{{ asset('img/breadcrumb-bg.jpg')}}">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="breadcrumb-text">
                        <h2>Evenement</h2>
                        <div class="bt-option">
                            <a href="#">Home</a>
                            <span>Evenement</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- Team Section Begin -->
    <section class="team-section spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="team-title">
                        <div class="section-title">
                            <span>NOS EVENEMENTS</span>
                            <h2>Défiez vos limites, rejoignez l'action!</h2>
                        </div>
                        <div class="about-bar">
                            <a href="{{ path('app_ticket_front_new')}}" class="primary-btn btn-normal appoinment-btn">Mes Tickets</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">

                <div class="ts-slider owl-carousel">
                    {% for evenement in evenements %}

                    <div class="col-lg-4">

                        <div  class="ts-item set-bg" >
                            <a href="{{ path('app_evenement_front_show', {'id': evenement.id}) }}">
                                <img src="{{ asset('uploads/evenement/' ~ evenement.imageEvenement) }}" alt="Evenement Image">
                            </a>

                            <div class="ts_text">
                                <h4  style="color: #f36100;">{{ evenement.nom }}</h4>
                                <span> {{ evenement.dateEvenement ? evenement.dateEvenement|date('D') : '' }}{{ evenement.dateEvenement ? evenement.dateEvenement|date('d') : '' }},{{ evenement.dateEvenement ? evenement.dateEvenement|date('M') : '' }}</span>
                                <span>{{ evenement.dateEvenement ? evenement.dateEvenement|date('h:i') : '' }}</span>



                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>


    </section>
    <!-- Team Section End -->
{% endblock %}

templates/evenement_front/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Evenement{% endblock %}

{% block body %}
    <h1>Create new Evenement</h1>

    {{ include('evenement_front/_form.html.twig') }}

    <a href="{{ path('app_evenement_front_index') }}">back to list</a>
{% endblock %}

templates/evenement_front/show.html.twig
{% extends 'base1.html.twig' %}

{% block title %}Evenement{% endblock %}

{% block body %}




    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-section set-bg" data-setbg="{{ asset('img/breadcrumb-bg.jpg')}}">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="breadcrumb-text">
                        <h2>Evenement</h2>
                        <div class="bt-option">
                            <a href="#">Home</a>
                            <a href="{{ path('app_evenement_front_index') }}"><span>Evenement</span></a>
                            <a ><span>Details Evenement</span></a>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->



    <!-- About US Section Begin -->
    <section class="aboutus-section">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-6 p-0">
                    <div style="background-image: url('{{ asset('uploads/' ~ evenement.imageEvenement) }}'); height: 640px; width: 760px;">
                        <a href="{{ path('app_evenement_front_show', {'id': evenement.id}) }}">
                            <img src="{{ asset('uploads/evenement/' ~ evenement.imageEvenement) }}" style="height: 100%; width: 100%;" alt="Evenement Image">
                        </a>
                    </div>
                </div>


                <div class="col-lg-6 p-0">
                    <div class="about-text">
                        <div class="section-title">
                            <h2 style="color: #f36100; font-size: 24px; margin-bottom: 10px;">{{ evenement.nom }}</h2>
                            <div style="font-size: 18px; color: #555;">
                                <h4 style="margin-bottom: 5px;"><span style="color:  #777;">Location:</span> <span style="color:  #ccc;">{{ evenement.lieu }}</span></h4>
                                <p style="margin-bottom: 5px;">{{ evenement.dateEvenement ? evenement.dateEvenement|date('D') : '' }} {{ evenement.dateEvenement ? evenement.dateEvenement|date('d') : '' }}, {{ evenement.dateEvenement ? evenement.dateEvenement|date('M') : '' }} | {{ evenement.dateEvenement ? evenement.dateEvenement|date('h:i') : '' }}</p>
                            </div>
                        </div>
                        <div class="at-desc" style="font-size: 16px; color: #333;">
                            <p>{{ evenement.description }}</p>
                        </div>
                        <div class="about-bar">
                            {% for ticket in evenement.tickets %}
                                <a href="{{ path('app_ticket_front_show', {'id': ticket.id}) }}" class="primary-btn btn-normal appoinment-btn">Participer</a>
                            {% endfor %}
                        </div>

                    </div>
                </div>

            </div>
            </div>

        </div>
        <iframe class="position-relative rounded w-100 h-100"
                src="https://maps.google.com/maps?q={{ evenement.lieu }}&amp;ie=UTF8&amp;iwloc=&amp;output=embed"
                frameborder="0" style="min-height: 650px; border:0; width: 200%;" allowfullscreen="" aria-hidden="false"
                tabindex="0"></iframe>
    </section>
    <!-- About US Section End -->


{% endblock %}